(defun howcompute (a b c)
	(cond ((= c (+ a b)) 'ADDED)
		((= c (- a b)) 'SUBTRACTED)
		((= c (- b a)) 'SUBTRACTED)
		((= c (* a b)) 'MULTIPLIED)
		((= c (/ a b)) 'DIVIDED)
		((= c (/ b a)) 'DIVIDED)
		(t 'DONT-KNOW)
		)
	)